### PR TITLE
Added image for another example (HSV example)

### PR DESCRIPTION
**Pull request by prajy**
Question: would it be better for multiple pull requests after small changes or just one pull request after doing substantial changes?

### CODE REVIEW

**Comment by prajy** [comment]
Also, what do you guys use to add new pages and edit it. Do you use raw html? I tried to add a new rst file for another page but could not get it working.

**Comment by TuringsEgo** [comment]
We make a new .rst, then build it (make html). It's put in .build.

**Comment by Twinters007** [comment]
First, take a screenshot. That image looks terrible. `gnome-screenshot -w -d 5` will give you 5 seconds to click on the window, then screenshot that window.

Generally you make a PR when you have a new 'feature'. So if you are fixing one feature, 1 PR is good. Features sometime span multiple files, like adding examples, for example. So this stuff would work well in your last PR, but its no big deal.
 
You have to add the rst to index.rst as well. That's probably why it isn't showing up if you're looking at the local docs.

**Comment by TuringsEgo** [comment]
I have Tim worry abour index.rst :)

**Comment by prajy** [comment]
Yeah, snipping tool took made the quality pretty crap. I'll use the terminal or maybe Snagit once I get home. I added the install method for python 3 in readme. What do you guys think would be better, GPU acceleration or camera settings (exposure,brightness). I know how to do camera settings for linux and GPU accel for the TX1. Or maybe I should do something else?

**Comment by Twinters007** [comment]
Snipping tool made the quality bad? That's really surprising...

**Comment by prajy** [comment]
I was about to so say some legit answer and then I realized the sarcasm...

**Comment by Twinters007** [comment]
No I'm actually surprised.

**Comment by prajy** [comment]
These ... can have way too many meanings...

**Comment by prajy** [comment]
Are you a student or a mentor? What team are you on?

**Comment by Twinters007** [comment]
1418, Mentor

**Comment by TuringsEgo** [comment]
1706 mentor here

**Comment by prajy** [comment]
How do I pull this project into my fork to get my fork updated in github?

**Comment by Twinters007** [comment]
In your fork, you can do git pull if your remotes are set up correctly. If not 
`git remote add upstream https://github.com/FRC-PDR/ProgrammingDoneRight` then `git pull upstream master`

**Comment by prajy** [comment]
can't seem to get it any better quality. The image itself is probably not the best quality and scaled down it gets worse.

**Comment by prajy** [comment]
When opening up the website locally, the images get resized and it looks better. This one is better than the original by a bit too

**Comment by prajy** [comment]
I tried taking a picture with my phone but the quality messes up. Could you try compiling my fork?

**Comment by Twinters007** [comment]
Upload the screen grap

**Comment by prajy** [comment]
screen shot 2017-03-23 at 5 25 27 pm
screen shot 2017-03-23 at 5 25 50 pm

These are quality as shown

**Comment by Twinters007** [comment]
I see those. Did you take a screenshot with the command I gave? The image with your phone is bad

**Comment by prajy** [comment]
Clicking on the image for a zoom in will show the regular image uploaded though

**Comment by prajy** [comment]
I used my mac command shift 4 for the screenshot

**Comment by Twinters007** [comment]
.....That's not the screenshot from a mac though...or else the window wouldn't be skewed 😂

**Comment by prajy** [comment]
The command you suggested does not work for me

**Comment by prajy** [comment]
I drew the lines xD

**Comment by Twinters007** [comment]
? In the current image, isn't that running Ubuntu?

**Comment by prajy** [comment]
OH that window. That just how the original image was taken

**Comment by Twinters007** [comment]
Yeah. I want to see the screenshot

**Comment by prajy** [comment]
This is the original image. It was taken skewed.
image0000001

The other images are the resized ones

**Comment by Twinters007** [comment]
https://gitter.im/FRC-PDR/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by prajy** [comment]
I gtg for a bit. Going to robotics. Ill be back

**Pull request closed without merging**
