### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by prajy**
These are able to be merged. Should have the new updates. I added the boiler image examples from some file, I somehow did not have it before.

### CODE REVIEW

**Comment by Twinters007** [comment]
Why did you open this one?

**Comment by prajy** [comment]
The other one, I did not pull it before adding my stuff

**Comment by prajy** [comment]
I pulled into a new branch and edited it. Did you fix the other one or did was those my changes? Sorry for the extra one then, I am not too familiar with github.

**Comment by Twinters007** [comment]
Yeah I fixed the other one

**Pull request closed without merging**
